#!/usr/bin/env python

import argparse
import sys

from ed_object_models.conversion_sdf import main

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert custom ED YAML model to SDF")
    parser.add_argument("models", type=str, nargs="+")
    parser.add_argument("--recursive", default=False, action="store_true")
    arguments = parser.parse_args()
    models = arguments.models
    recursive = arguments.recursive

    for model in models:
        errc = main(model, recursive=recursive)
        if errc != 0:
            sys.exit(errc)
