#!/usr/bin/env python

import sys
import argparse

from ed_object_models.conversion_sdf import main

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert custom ED YAML model to SDF")
    parser.add_argument("model", type=str)
    parser.add_argument("--recursive", default=False, action="store_true")
    arguments = parser.parse_args()
    model = arguments.model
    recursive = arguments.recursive

    sys.exit(main(model, recursive=recursive))
